title: Lui Habl
description: This is a personal page to write down my thoughts.

baseurl: ""
color-scheme: "#007bff" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
